#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: App\Controller\AppMainController:index
home:
  path: /home
  controller: App\Controller\AppMainController:index
blog:
  path: /blog
  controller: App\Controller\AppMainController:blog
adminpanel:
  path: /adminpanel
  controller: App\Controller\AdminPanelController:index
adminpanelsess:
  path: /adminpanel/newsession/
  controller: App\Controller\AdminPanelController:newsession
adminlogout:
  path: /adminpanel/logout/
  controller: App\Controller\AdminPanelController::logout
newarticle:
  path: /adminpanel/newarticle/
  controller: App\Controller\AdminPanelController::newBlog
savenewblog:
  path: /adminpanel/savenewblog/
  controller: App\Controller\AdminPanelController::saveNewBlog
articles:
  path: /adminpanel/articles/
  controller: App\Controller\AdminPanelController::articles
deletearticle:
  path: /adminpanel/deletearticle/{blogId}
  controller: App\Controller\AdminPanelController::deleteBlog
updatearticle:
  path: /adminpanel/updatearticle/{blogId}
  controller: App\Controller\AdminPanelController::updateBlog
saveupdateblog:
  path: /adminpanel/saveupdateblog/
  controller: App\Controller\AdminPanelController::saveUpdateBlog
